import type { Lang } from './i18n.js';

/**
 * The words of people and conversations: handles, @mentions, suggestions'
 * conversations and reviews, Issues and the inbox. Kept beside i18n.ts, in
 * the same form, Hebrew first.
 */
const THREAD_STRINGS = {
  // Handles
  username: { he: 'שם משתמש', en: 'Username' },
  usernameHelp: { he: 'אותיות לטיניות, ספרות ומקף. כך יתייגו אתכם: ‎@שם', en: 'Latin letters, digits and hyphens. This is how people @mention you.' },
  usernameFree: { he: 'פנוי', en: 'Available' },
  usernameChecking: { he: 'בודקים…', en: 'Checking…' },
  usernameTry: { he: 'אולי', en: 'How about' },
  usernameChange: { he: 'שינוי שם המשתמש', en: 'Change username' },
  usernameChangeNote: {
    he: 'הכתובת הישנה והתיוגים הישנים ימשיכו להוביל אליכם. אפשר לשנות פעם ביממה.',
    en: 'Your old address and old @mentions keep leading to you. You can change it once a day.',
  },
  usernameSaved: { he: 'נשמר.', en: 'Saved.' },
  save: { he: 'שמירה', en: 'Save' },
  // People
  profile: { he: 'הדף שלי', en: 'Your page' },
  memberSince: { he: 'חבר מאז', en: 'Member since' },
  steward: { he: 'מנהל', en: 'Steward' },
  trusted: { he: 'אמין', en: 'Trusted' },
  bot: { he: 'בוט', en: 'bot' },
  suspended: { he: 'מושעה', en: 'Suspended' },
  movedFrom: { he: 'שם המשתמש הקודם היה', en: 'This person used to be' },
  statSuggestions: { he: 'הצעות', en: 'Suggestions' },
  statMerged: { he: 'אושרו', en: 'Approved' },
  statReviews: { he: 'סקירות', en: 'Reviews' },
  statIssues: { he: 'דיווחים', en: 'Issues' },
  statComments: { he: 'תגובות', en: 'Comments' },
  activity: { he: 'פעילות', en: 'Activity' },
  noActivity: { he: 'אין עדיין פעילות ציבורית.', en: 'No public activity yet.' },
  actSuggestion: { he: 'הציע', en: 'suggested' },
  actReview: { he: 'סקר את', en: 'reviewed' },
  actIssue: { he: 'פתח את', en: 'opened' },
  actComment: { he: 'הגיב על', en: 'commented on' },
  talkOf: { he: 'דף השיחה של', en: 'the talk page of' },
  // Writing
  write: { he: 'כתיבה', en: 'Write' },
  preview: { he: 'תצוגה מקדימה', en: 'Preview' },
  nothingToPreview: { he: 'אין מה להציג.', en: 'Nothing to preview.' },
  composerHint: { he: '‎@ לתייג אדם · ‎# להפנות להצעה או דיווח · Ctrl+Enter לשליחה', en: '@ to mention someone · # to link a suggestion or issue · Ctrl+Enter to send' },
  leaveComment: { he: 'כתבו תגובה…', en: 'Leave a comment…' },
  comment: { he: 'תגובה', en: 'Comment' },
  reply: { he: 'תשובה', en: 'Reply' },
  edit: { he: 'עריכה', en: 'Edit' },
  edited: { he: 'נערך', en: 'edited' },
  cancel: { he: 'ביטול', en: 'Cancel' },
  hiddenComment: { he: 'התגובה הוסתרה.', en: 'This comment was hidden.' },
  signInToJoin: { he: 'כדי להשתתף בשיחה צריך להתחבר.', en: 'Sign in to join the conversation.' },
  noOneFound: { he: 'לא נמצא', en: 'No match' },
  // Timeline
  commented: { he: 'הגיב', en: 'commented' },
  opened: { he: 'פתח', en: 'opened this' },
  openedSuggestion: { he: 'פתח את ההצעה', en: 'opened this suggestion' },
  submitted: { he: 'שלח לסקירה', en: 'sent this for review' },
  submittedLive: { he: 'העלה ישירות (משתמש אמין)', en: 'put this live at once (trusted)' },
  sentBack: { he: 'ביקש שינויים', en: 'requested changes' },
  approved: { he: 'אישר', en: 'approved these changes' },
  reviewedComment: { he: 'סקר', en: 'reviewed' },
  merged: { he: 'מיזג לקטלוג', en: 'merged this into the catalog' },
  withdrawn: { he: 'משך את ההצעה', en: 'withdrew this' },
  reverted: { he: 'ביטל את השינוי ב', en: 'undid this in' },
  closedDone: { he: 'סגר כבוצע', en: 'closed this as completed' },
  closedNotPlanned: { he: 'סגר כלא מתוכנן', en: 'closed this as not planned' },
  closedBy: { he: 'בזכות', en: 'in' },
  reopened: { he: 'פתח מחדש', en: 'reopened this' },
  renamed: { he: 'שינה את הכותרת', en: 'changed the title' },
  labeled: { he: 'הוסיף תווית', en: 'added' },
  unlabeled: { he: 'הסיר תווית', en: 'removed' },
  assigned: { he: 'שייך את', en: 'assigned' },
  selfAssigned: { he: 'לקח על עצמו', en: 'self-assigned this' },
  unassigned: { he: 'הסיר את השיוך של', en: 'unassigned' },
  reviewRequested: { he: 'ביקש סקירה מ', en: 'requested a review from' },
  reviewRequestedAuto: { he: 'בקשת סקירה נשלחה אוטומטית לשומרי הסט:', en: "The set's keepers were asked to review:" },
  reviewRequestRemoved: { he: 'ביטל את בקשת הסקירה מ', en: 'removed the review request for' },
  referenced: { he: 'הזכיר את זה ב', en: 'mentioned this in' },
  referencedCloses: { he: 'קישר הצעה שתסגור את זה:', en: 'linked a suggestion that will close this:' },
  madePrivate: { he: 'הפך לפרטי', en: 'made this private' },
  madePublic: { he: 'הפך לציבורי', en: 'made this public' },
  someone: { he: 'מישהו', en: 'Someone' },
  reader: { he: 'קורא ללא חשבון', en: 'A reader without an account' },
  onField: { he: 'על', en: 'on' },
  resolved: { he: 'נפתר', en: 'Resolved' },
  resolve: { he: 'סימון כנפתר', en: 'Resolve' },
  unresolve: { he: 'פתיחה מחדש', en: 'Unresolve' },
  showResolved: { he: 'הצגת השיחה', en: 'Show conversation' },
  // State
  stateOpen: { he: 'פתוח', en: 'Open' },
  stateClosed: { he: 'סגור', en: 'Closed' },
  stateMerged: { he: 'מוזג', en: 'Merged' },
  stateSentBack: { he: 'נדרשים שינויים', en: 'Changes requested' },
  stateWithdrawn: { he: 'נמשך', en: 'Withdrawn' },
  stateDraft: { he: 'טיוטה', en: 'Draft' },
  // Suggestions
  suggestionsTitle: { he: 'הצעות', en: 'Suggestions' },
  suggestionsLead: {
    he: 'כל שינוי בקטלוג מתחיל כהצעה: שיחה, סקירה, ואישור של שומרי הסט.',
    en: 'Every change to the catalog starts as a suggestion: a conversation, a review, and a keeper’s approval.',
  },
  tabConversation: { he: 'שיחה', en: 'Conversation' },
  tabChanges: { he: 'השינויים', en: 'Changes' },
  reviewers: { he: 'סוקרים', en: 'Reviewers' },
  noReviewers: { he: 'אין עדיין', en: 'None yet' },
  requestReview: { he: 'בקשת סקירה', en: 'Request review' },
  reRequest: { he: 'לבקש שוב', en: 'Re-request' },
  awaiting: { he: 'ממתין', en: 'Awaiting' },
  fixes: { he: 'סוגר דיווחים', en: 'Closes issues' },
  fixesHint: { he: 'כתבו "סוגר ‎#12" או "Fixes #12" בתיאור.', en: 'Write "Fixes #12" in the description.' },
  review: { he: 'סקירה', en: 'Review' },
  reviewChanges: { he: 'סקירת השינויים', en: 'Review changes' },
  verdictComment: { he: 'הערה', en: 'Comment' },
  verdictCommentHint: { he: 'משוב כללי בלי להחליט.', en: 'General feedback, deciding nothing.' },
  verdictApprove: { he: 'אישור', en: 'Approve' },
  verdictApproveHint: { he: 'השינוי נכנס לקטלוג.', en: 'The change goes into the catalog.' },
  verdictRequestChanges: { he: 'בקשת שינויים', en: 'Request changes' },
  verdictRequestChangesHint: { he: 'ההצעה חוזרת לכותב עם ההערות.', en: 'It goes back to its writer with your notes.' },
  submitReview: { he: 'שליחת הסקירה', en: 'Submit review' },
  pendingComments: { he: 'הערות על שדות שיישלחו עם הסקירה', en: 'Field comments to send with the review' },
  commentField: { he: 'הערה על השדה', en: 'Comment on this field' },
  addToReview: { he: 'הוספה לסקירה', en: 'Add to review' },
  onlyKeepers: { he: 'אישור ובקשת שינויים הם של שומרי הסט.', en: 'Approving and requesting changes is for the set’s keepers.' },
  withdraw: { he: 'ביטול ההצעה', en: 'Withdraw this suggestion' },
  withdrawConfirm: { he: 'לבטל את ההצעה? היא תיסגר בלי שינוי. אפשר לפתוח אותה מחדש אחר כך.', en: 'Withdraw this suggestion? It closes with nothing changed. You can reopen it later.' },
  reopenNote: { he: 'ההצעה נמשכה. אפשר לפתוח אותה מחדש, והיא תחזור לבדיקה.', en: 'This was withdrawn. Reopen it and it goes back for review.' },
  undoChange: { he: 'ביטול השינוי', en: 'Undo this change' },
  undoNote: { he: 'השינוי נכנס לקטלוג. ביטול מחזיר כל פריט למה שהיה לפניו.', en: 'This change is in the catalog. Undoing it puts every item back as it was.' },
  undoConfirm: { he: 'לבטל את השינוי הזה? כל פריט יחזור למה שהיה לפניו.', en: 'Undo this change? Every item goes back as it was.' },
  editTitle: { he: 'עריכת הכותרת', en: 'Edit title' },
  description: { he: 'תיאור', en: 'Description' },
  noDescription: { he: 'אין תיאור.', en: 'No description.' },
  newItemLine: { he: 'פריט חדש', en: 'New item' },
  openOnReview: { he: 'בדף הסקירה', en: 'On the review page' },
  // Issues
  issuesTitle: { he: 'דיווחים', en: 'Issues' },
  issuesLead: {
    he: 'טעויות, עמודים חסרים, בעיות בהקלטות ושאלות: כל דיווח הוא שיחה עם מספר, תוויות ואחראים.',
    en: 'Mistakes, missing pages, recording problems and questions: each issue is a numbered conversation, with labels and people on it.',
  },
  newIssue: { he: 'דיווח חדש', en: 'New issue' },
  issueType: { he: 'מה הבעיה?', en: 'What is it about?' },
  title: { he: 'כותרת', en: 'Title' },
  body: { he: 'פרטים', en: 'Details' },
  about: { he: 'על', en: 'About' },
  aboutItem: { he: 'על הפריט', en: 'About the item' },
  itemIdHint: { he: 'מזהה פריט (rh-…) או קישור, לא חובה', en: 'An item id (rh-…) or its link, optional' },
  privateType: { he: 'דיווח מסוג זה פרטי: רק המנהלים ושומרי הסט יראו אותו.', en: 'This kind of issue is private: only stewards and the set’s keepers see it.' },
  publicNote: { he: 'דיווחים גלויים לכולם, כמו ב־GitHub.', en: 'Issues are public, as on GitHub.' },
  reportPublic: {
    he: 'הדיווח גלוי לכולם באתר (בלי שמכם), חוץ מדיווח על זכויות יוצרים או תוכן פוגע. אל תכתבו כאן פרטים אישיים.',
    en: 'Reports are public on the site (without your name), except those about rights or offensive content. Leave out personal details.',
  },
  fullIssue: { he: 'או פתחו דיווח מלא, עם כותרת ותיוגים', en: 'Or open a full issue, with a title and @mentions' },
  submitIssue: { he: 'פתיחת הדיווח', en: 'Open the issue' },
  private: { he: 'פרטי', en: 'Private' },
  labels: { he: 'תוויות', en: 'Labels' },
  noLabels: { he: 'אין', en: 'None' },
  assignees: { he: 'אחראים', en: 'Assignees' },
  noAssignees: { he: 'אין עדיין', en: 'No one yet' },
  assignYourself: { he: 'לקחת על עצמי', en: 'assign yourself' },
  filterLabel: { he: 'תווית', en: 'Label' },
  filterType: { he: 'סוג', en: 'Type' },
  filterAssignee: { he: 'אחראי', en: 'Assignee' },
  filterAuthor: { he: 'כותב', en: 'Author' },
  filterReviewer: { he: 'סוקר', en: 'Reviewer' },
  filterSet: { he: 'סט', en: 'Set' },
  anyone: { he: 'כולם', en: 'Anyone' },
  nobody: { he: 'ללא אחראי', en: 'Assigned to nobody' },
  all: { he: 'הכול', en: 'All' },
  search: { he: 'חיפוש…', en: 'Search…' },
  clearFilters: { he: 'ניקוי המסננים', en: 'Clear filters' },
  nothingHere: { he: 'אין כאן כלום.', en: 'Nothing here.' },
  more: { he: 'עוד', en: 'More' },
  closeDone: { he: 'סגירה כבוצע', en: 'Close as completed' },
  closeNotPlanned: { he: 'סגירה כלא מתוכנן', en: 'Close as not planned' },
  closeWithComment: { he: 'סגירה עם התגובה', en: 'Close with comment' },
  reopen: { he: 'פתיחה מחדש', en: 'Reopen' },
  makePrivate: { he: 'להפוך לפרטי', en: 'Make private' },
  makePublic: { he: 'להפוך לציבורי', en: 'Make public' },
  fixedBy: { he: 'הצעות שסוגרות אותו', en: 'Suggestions that close it' },
  subscribe: { he: 'מעקב', en: 'Subscribe' },
  unsubscribe: { he: 'הפסקת מעקב', en: 'Unsubscribe' },
  subscribedNote: { he: 'תקבלו עדכון בתיבה על כל תגובה ושינוי.', en: 'You get an inbox line for every comment and change.' },
  notSubscribedNote: { he: 'תקבלו עדכון רק אם יתייגו אתכם.', en: 'You only hear of it when you are mentioned.' },
  typeOf: { he: 'סוג', en: 'Type' },
  // The inbox
  inboxTitle: { he: 'התיבה', en: 'Inbox' },
  inboxLead: { he: 'תיוגים, בקשות סקירה, מה ששויך אליכם ומה שאתם עוקבים אחריו.', en: 'Mentions, review requests, what is assigned to you and what you follow.' },
  inboxEmpty: { he: 'אין מה לקרוא. יפה!', en: 'All caught up.' },
  unread: { he: 'לא נקראו', en: 'Unread' },
  markAllRead: { he: 'סימון הכול כנקרא', en: 'Mark all as read' },
  markRead: { he: 'נקרא', en: 'Done' },
  markUnread: { he: 'לא נקרא', en: 'Unread' },
  reasonMention: { he: 'תויגתם', en: 'Mentioned' },
  reasonReviewRequested: { he: 'בקשת סקירה', en: 'Review requested' },
  reasonAssigned: { he: 'שויך אליכם', en: 'Assigned' },
  reasonAuthor: { he: 'שלכם', en: 'Yours' },
  reasonComment: { he: 'תגובה', en: 'Comment' },
  reasonReview: { he: 'סקירה', en: 'Review' },
  reasonState: { he: 'שינוי מצב', en: 'State change' },
  reasonFollowed: { he: 'במעקב', en: 'Following' },
  times: { he: 'פעמים', en: 'times' },
  signInForInbox: { he: 'התחברו כדי לראות את התיבה.', en: 'Sign in to see your inbox.' },
} as const satisfies Record<string, { he: string; en: string }>;

export type ThreadStringKey = keyof typeof THREAD_STRINGS;

export function tt(lang: Lang, key: ThreadStringKey): string {
  return THREAD_STRINGS[key][lang];
}
